spring:
  application:
    name: producer-service
  rabbitmq:
    broker-url: tcp://127.0.0.1:5672
    username: someuser
    password: somepassword
    host: localhost
  listener:
    simple:
      default-requeue-rejected: false
